#!/usr/bin/env python3
"""
DEEPEX v4 Audit - Simplified for Windows
"""
import sys
import os
from pathlib import Path

# Add DEEPEX to path
deepex_path = Path("L:/nicedev-Project/MindWarehouse-Project/DEEPEX")
sys.path.insert(0, str(deepex_path))

from DEEPEX_v4_IMPLEMENTATION import DEEPEXv4, Project
from datetime import datetime

def count_loc(path: str) -> int:
    """Count lines of code"""
    total_loc = 0
    exclude_dirs = {'.venv', 'venv', '.git', '__pycache__', 'node_modules', 'dist', 'build'}
    exclude_extensions = {'.png', '.jpg', '.jpeg', '.gif', '.ico', '.svg', '.woff', '.woff2', '.ttf', '.mp4', '.mp3', '.pdf'}
    
    for root, dirs, files in os.walk(path):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for file in files:
            file_ext = os.path.splitext(file)[1].lower()
            if file_ext in exclude_extensions:
                continue
            file_path = os.path.join(root, file)
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    total_loc += len(f.readlines())
            except:
                continue
    return total_loc

def main():
    project_path = Path("L:/nicedev-Project/MW-Vision")
    print("="*60)
    print("DEEPEX v4 AUDIT - MW-VISION")
    print("="*60)
    
    # Count LOC
    print("Counting lines of code...")
    loc = count_loc(str(project_path))
    print(f"Total LOC: {loc:,}")
    
    # Create Project
    project = Project(
        name="MW-Vision",
        path=str(project_path),
        language="Mixed (TypeScript/Python)",
        size_loc=loc,
        context="production"
    )
    
    # Run DEEPEX
    print("Running DEEPEX v4 evaluation...")
    evaluator = DEEPEXv4(context="production")
    result = evaluator.evaluate(project)
    
    # Results
    print("\n" + "="*60)
    print("ITERATION 1 RESULTS")
    print("="*60)
    print(f"Overall Score: {result.overall_score:.1f}%")
    print(f"Confidence: {result.confidence:.2f}")
    print(f"Version: {result.version}")
    
    print("\nCategory Scores:")
    for cat, score in sorted(result.category_scores.items(), key=lambda x: x[1]):
        print(f"  {cat:30} {score:6.1f}%")
    
    print("\nRecommendations:")
    for i, rec in enumerate(result.recommendations, 1):
        print(f"  {i}. {rec}")
    
    print("\nFindings:")
    for i, f in enumerate(result.findings[:20], 1):
        severity = f.get('severity', 'INFO')
        issue = f.get('issue', 'Unknown')
        print(f"  {i:2}. [{severity}] {issue}")
    
    # Save report
    report = f"""# DEEPEX v4 Audit Report - MW-Vision

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Auditor:** DEEPEX v4.0.0
**Project:** MW-Vision

---

## EXECUTIVE SUMMARY

| Metric | Value |
|--------|-------|
| Overall Score | {result.overall_score:.1f}% |
| Confidence | {result.confidence:.2f} |
| LOC | {loc:,} |
| Version | {result.version} |

---

## CATEGORY SCORES

| Category | Score |
|----------|-------|
"""
    for cat, score in sorted(result.category_scores.items(), key=lambda x: x[1]):
        report += f"| {cat} | {score:.1f}% |\n"
    
    report += """
---

## RECOMMENDATIONS

"""
    for i, rec in enumerate(result.recommendations, 1):
        report += f"{i}. {rec}\n"
    
    report += """
---

## TOP FINDINGS

"""
    for i, f in enumerate(result.findings[:20], 1):
        severity = f.get('severity', 'INFO')
        issue = f.get('issue', 'Unknown')
        file_path = f.get('file', 'N/A')
        report += f"{i}. [{severity}] {issue}\n   File: {file_path}\n\n"
    
    report += "*Generated by DEEPEX v4.0.0*"
    
    report_path = project_path / "DEEPEX_AUDIT_REPORT.md"
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"\nReport saved to: {report_path}")
    print("\nDEEPEX audit completed!")

if __name__ == "__main__":
    main()
